export const file_prefix="file::";
export const file_load="";
export const file_exists='file already exists in server data';
export const file_end_load="::^end^::";
export const video_prefix="::video::";
export const stream_end="::streamEnd::";
export const icons_prefix="::icons::";
export const disconect_prefix="Server:  disconect from server...";
export const limit_msg=500;
export const english = /^[a-zA-Z0-9!@#$%^&*()_+\-=[\]{};':"\\|,.<>/?]*$/; 